spring:
  thymeleaf:
    cache: false
  application:
    name: xiaotuzi
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://192.168.31.248:3306/stydy_system?serverTimezone=UTC&useUnicode=true&characterEncoding=utf8
    username: root
    password: 123456
    type: com.alibaba.druid.pool.DruidDataSource
  # Redis数据库索引（默认为0）
  main:
    allow-bean-definition-overriding: true
  redis:
    database: 0
    # Redis服务器地址
    host: 127.0.0.1
    # Redis服务器连接端口
    port:  6379
    # Redis服务器连接密码（默认为空）
    password: 12345
    # 连接池最大连接数（使用负值表示没有限制）
    pool:
    # 连接池最大阻塞等待时间（使用负值表示没有限制）
    # 连接池中的最大空闲连接
    # 连接池中的最小空闲连接
    # 连接超时时间（毫秒）
    timeout: 1000
    jedis:
      pool:
        max-idle: 200
        min-idle: 0
        max-wait: -1
        max-active: 8
  #session存储格式为redis
  session:
    store-type: redis
  rabbitmq:
    host: 192.168.31.248
    port: 5672
    username: admin
    password: password

# 配置日志
logging:
  level:
    root: info
    com:
      example:
        dao: debug

#表示全局主键都采用该策略（如果全局策略和局部策略都有设置，局部策略优先级高）
#mybatis-plus:
#  global-config:
#    db-config:
#      id-type: auto
##      field-strategy: not_empty
#      logic-delete-value: 0
#      logic-not-delete-value: 1

#mybatis-plus:
#  configuration:
#    map-underscore-to-camel-case: true
#    auto-mapping-behavior: full
#    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
#  mapper-locations: classpath*:mapper/**/*Mapper.xml
#  global-config:
#    # 逻辑删除配置
#    db-config:
#      # 删除前
#      logic-not-delete-value: 1
#      # 删除后
#      logic-delete-value: 0